# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{push-notify}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew M. Boedicker"]
  s.date = %q{2010-07-01}
  s.description = %q{Notified pubsubhubbub hubs of updated content}
  s.email = %q{matthewm@boedicker.org}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "COPYING",
     "README.textile",
     "Rakefile",
     "VERSION",
     "lib/push-notify.rb",
     "push-notify.gemspec"
  ]
  s.homepage = %q{http://github.com/mmb/push-notify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Notified pubsubhubbub hubs of updated content}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

